### ISSUE TITLE
Развитие проекта

### ISSUE THREAD

**Issue by Alldar** [ldmco/KsenMart#43]
В связи с этим:
http://joomlaforum.ru/index.php/topic,306149.msg1520583.html#msg1520583

Стоит ли ждать развитее проекта дальше или можно на нем ставить крест?

**Comment by TakT** [comment]
Здравствуйте!

Это ни как не влияет на Ксенмарт. По мере возможностей будут вноситься баг фиксы, обрабатываться пул реквесты, собираться сборки и тд. 

Всегда будем рады помощи в улучшении проекта со стороны общественности.

**Comment by zelslon** [comment]
Вообще это огромная глупость бывшего работника студии.
Он удалил сайт имея доступы и написал на странице разных гадостей!

Вопрос спора был в 3000 руб за косячно сделанную работу. По факту этого инцидента произведены действия и приняты меры. 
Хотел вообще в органы заяву отдать, но пожалел парня ибо судимость на всю жизнь была бы потом...
