### ISSUE TITLE
Просмотр отзыва о магазине

### ISSUE THREAD

**Issue by stsasus** [ldmco/Ksenmart#56]
При переходе по ссылке подробнее в отзывах ошибка Fatal error: Class 'KsenmartHelper' not found in C:\OpenServer\domains\ksena\templates\ksenmartcolorful\html\com_ksenmart\comments\comment.php on line 15

Страница все отзывы выдает KSM_REVIEWS_LIST_NO_COMMENTS
хотя отзывы есть

**Comment by TakT** [comment]
Уже пофикшен, выкатится в новой сборке, либо смотрите в ветке https://github.com/ldmco/Ksenmart/tree/dev

**Comment by stsasus** [comment]
ок
