### ISSUE TITLE
Товара нет в наличии, но он добавляется в корзину.

### ISSUE THREAD

**Issue by Dexternova** [ldmco/Ksenmart#65]
Товара нет в наличии, но он добавляется в корзину. 
В карточке товара не исчезает кнопка "добавить в корзину". а при ее нажатии происходит добавление товара в корзину. 
Настройка "Вести учет по складу" на это ни как не влияет(ничего не меняется)
В поле "на складе" выставлено значение "0".

**Comment by Yoji** [comment]
Видимо дело в шаблоне. Что за шаблон?

**Comment by Dexternova** [comment]
KsenMart Colorful

**Comment by Dexternova** [comment]
да. дело в шаблоне. поменял шаблон на KMTEMPLATE - заработало. но мне нужно что бы работало в KsenMart Colorful - как это вылечить?

**Comment by Yoji** [comment]
Самый простой способ заменить в шаблоне файл templates/ksenmartcolorful/html/com_ksenmart/product/product_prices.php
на тот что из ксенмарта:
/components/com_ksenmart/views/product/tmpl/product_prices.php

Насколько я помню, они только проверкой на наличие на складе и отличаются.

**Comment by Dexternova** [comment]
помогло)

**Comment by Yoji** [comment]
Гуд)
