### ISSUE TITLE
В шаблоне KsenMart Colorful не корректно отображается модуль "Быстрый фильтр"

### ISSUE THREAD

**Issue by Dexternova** [ldmco/Ksenmart#66]
Проблемы следующие:
контейнер не растягивается в зависимости от кол-ва фильтров
отображаются не все свойства в фильтре(например картинка с цветом.) 

Проверил в другом шаблоне( KMTEMPLATE ) - работает отлично. 
Как решить эту проблему?

**Comment by Yoji** [comment]
Можно ссылку на проблемную страницу?

**Comment by Dexternova** [comment]
http://ori.tw1.ru/shop.html

**Comment by Dexternova** [comment]
ранее я вписал в css: 
 #leftSidebar .ksenmart-search
height: 1400px;
padding-left: 15px!important;

но это не помогло(

**Comment by Yoji** [comment]
Те изменения отмените.
В файле /templates/ksenmartcolorful/html/mod_km_filter/default.php
строку:
<ul class="nav nav-list">
замените на:
<ul class="nav nav-list clearfix">

**Comment by Dexternova** [comment]
заменил.
размер контейнер впорядке
НО изображения свойств все равно не отображаются.

**Comment by Yoji** [comment]
В принципе можно так же скопировать стандартный файл:
mod_km_filter/tmpl/default.php
и заменить им тот что в шаблоне, но на всякий случай копию сделать того файла что в шаблоне, а то не помню, чем они там отличаются.

**Comment by Dexternova** [comment]
спасибо. после замены все заработало, как нужно!

**Comment by web-installer** [comment]
http://www.dvernoyclub.ru/ В карте товара срабатует фильтр а в каталоге нет! Подскажитепричину!
