### ISSUE TITLE
Косяк с поиском товаров.

### ISSUE THREAD

**Issue by Orsey** [ldmco/Ksenmart#69]
Поиск товаров работает немного неверное, а именно ищет даже не опубликованные товары, ну и соответственно отображает их в результатах поиска.

**Comment by Dexternova** [comment]
И у меня то же самое. Как исправить?

**Comment by Orsey** [comment]
Поправить запрос  к базе данных нужно наверное...

**Comment by Orsey** [comment]
В последней версии я так понял это решение уже не прокатит, даже если проблема осталась, так как нет такого файла, а вот для вашей версии сюдя по всему сгодиться.
Вот что ответил разработчик и это решило проблему поиска

в файле:
com_ksenmart/site/models/search.php
нужно в 113 строке заменить
WHERE ";
 на 
WHERE p.published=1 and (";
и после 124 строки вставить:
$query .= ')';
