### ISSUE TITLE
Проблема со страницей настроек SEO

### ISSUE THREAD

**Issue by Orsey** [ldmco/Ksenmart#75]
В последней версии при попытке попасть на страницу настроек SEO в админке получаю следующую ошибку:

"500 Макет default не найден" и стандартное предложение вернуться на главную страницу панели управления Joomla.

**Comment by TakT** [comment]
fix https://github.com/ldmco/Ksenmart/commit/0f57bd9a4393220d9a117659e1a2950b524b09aa
